### ISSUE TITLE
This thing does not work

### ISSUE THREAD

**Issue by SFinctor** [marcograss/routerosbackuptools#22]
** Decrypt Backup **
** Backup Info **
RouterOS Encrypted Backup (aes128-ctr-sha256)
Length: 221641 bytes
Salt (hex): [b6, 35, a9, 3b, 63, 16, b6, 21, 88, 84, 5b, b6, 6c, f1, 97, 4, b1, 3c, c9, 3b, f5, 33, 9, bb, 29, 2, b7, d1, 3f, 6c, f6, b3]
Signature: [fe, ff, ed, b9, 29, ee, 6e, 7, c1, db, ca, 64, 88, 81, 74, b7, 84, 70, b0, 6e, 70, 64, 0, d5, 9e, 88, c1, a4, 1f, e3, 47, 9d]
Magic Check (hex): c35aa30c
Correct password!
Decrypting...
Decrypted correctly
No such file or directory (os error 2)

**Comment by marcograss** [comment]
paste also the exact command you are executing please I will check
